services:
  # L'app PHP
  web-app:
    build: .
    ports:
      - "9000:80" # Port standard HTTP
    depends_on:
      - db

  # Ta BDD MariaDB (Rien ne change, c'est nickel)
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toyboxing
    volumes:
      - db_data:/var/lib/mysql

  # Ton interface de gestion
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8888:80"
    environment:
      - PMA_HOST=db

volumes:
  db_data:
